2024-12-09 03:58:23,607 [INFO] Using device: cpu
2024-12-09 03:58:23,834 [INFO] Loaded 13999 images for train split
2024-12-09 03:58:23,854 [INFO] Loaded 1999 images for val split
/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /Users/seunadekunle/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100%|█████████████████████████████████████████████████████████████████| 528M/528M [00:08<00:00, 65.2MB/s]
Epoch 0:   0%|                                                                   | 0/438 [00:13<?, ?it/s]
Traceback (most recent call last):
  File "/Users/seunadekunle/school/567/style_classifier/src/training/train_darn.py", line 316, in <module>
    main()
  File "/Users/seunadekunle/school/567/style_classifier/src/training/train_darn.py", line 277, in main
    train_metrics = train_epoch(
  File "/Users/seunadekunle/school/567/style_classifier/src/training/train_darn.py", line 100, in train_epoch
    for batch in pbar:
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Users/seunadekunle/school/567/style_classifier/src/data/deepfashion_dataset.py", line 146, in __getitem__
    image = Image.open(img_path).convert("RGB")
  File "/Users/seunadekunle/miniconda3/envs/style_classifier/lib/python3.9/site-packages/PIL/Image.py", line 3469, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/seunadekunle/school/567/style_classifier/data_deepfashion/img/img/Patriotic_Mineral_Wash_Dress/img_00000022.jpg'
